name: Deploy
on:
  workflow_run:
    workflows: ["Test", "Release"]
    types:
      - completed

env:
  FLY_API_TOKEN: ${{secrets.FLY_API_TOKEN}}

jobs:
  deploy:
    name: Deploying nguji-backend
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
